import type { GetServerSideProps, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import LatestBlogs from "../components/LatestBlogs";
import { IPropDataArray } from "../interfaces/blog.interface";
// import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home = (props: IPropDataArray) => {
  return (
    <div>
      {/* <style jsx>
        {`
          h2 {
            font-size: 38px;
          }
          h3 {
            font-size: 28px;
          }
        `}
      </style> */}
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by Hunting coder" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hunting coder</h1>

        <div className={styles.imagewrap}>
          {/* <Image
            className={styles.myImg}
            src="/homeimg.jpg"
            width={237}
            height={158}
            alt="Home image"
          /> */}
          <img
            className={styles.myImg}
            src="/homeimg.jpg"
            width={237}
            height={158}
            alt="Home image"
          />
        </div>
        <p className={styles.description}>Let`s start with hunting coder</p>
        <LatestBlogs allBlogs={props.allBlogs} />
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;

/**
 *
 * Server Side Generation
 * This gets called on every request
 *
 */
export const getServerSideProps: GetServerSideProps = async () => {
  // Fetch data from external API
  const res = await fetch(
    `http://localhost:1337/api/posts?sort[0]=updatedAt:desc&pagination[page]=1&pagination[pageSize]=5`
  );
  const { data: allBlogs } = await res.json();
  // Pass allBlogs to the page via props
  return { props: { allBlogs } };
};

/**
 *
 * Static Site Generation
 *
 */
// export const getStaticProps: GetStaticProps = async (context) => {
//   // // With Strapi API
//   // Fetch data from external API
//   const res = await fetch(
//     `http://localhost:1337/api/posts/${context.params?.slug}`
//   );
//   const { data: myBlog } = await res.json();
//   return {
//     props: { myBlog: myBlog },
//   };

// // With static JSON file
//   const slug = context.params?.slug;
//   let myBlog = await fs.promises.readFile(`blogdata/${slug}.json`, "utf-8");
//   return {
//     props: { myBlog: JSON.parse(myBlog) },
//   };
// };
