import type { NextPage } from "next";
import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 38px;
          }
          h3 {
            font-size: 28px;
          }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by Hunting coder" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hunting coder</h1>

        <div className={styles.imagewrap}>
          {/* <Image
            className={styles.myImg}
            src="/homeimg.jpg"
            width={237}
            height={158}
            alt="Home image"
          /> */}
          <img
            className={styles.myImg}
            src="/homeimg.jpg"
            width={237}
            height={158}
            alt="Home image"
          />
        </div>

        <p className={styles.description}>Let`s start with hunting coder</p>
        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
